name: our_money
publish_to: none

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: '>=3.7.0'

dependencies:
  black_hole_flutter: ^1.0.1
  collection: ^1.15.0
  dartx: ^1.1.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  logger: ^1.3.0
  todo: ^2.0.0
  tuple: ^2.0.1

dev_dependencies:
  dart_code_metrics: ^5.0.1
  flutter_lints: ^2.0.1
